In [8]:
import tensorflow as tf
from tensorflow.keras import layers
import pandas as pd
import numpy as np
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical

In [15]:
from google.colab import files
uploaded = files.upload()

Saving nilai_mapel.csv to nilai_mapel (1).csv


In [18]:
import io
df = pd.read_csv(io.BytesIO(uploaded['nilai_mapel.csv']))
df.head()
# Dataset is now stored in a Pandas Dataframe

Matematika  Bahasa Indonesia  IPA  IPS  Bahasa Inggris  Penjaskes  \
0          77                65   82   93              74         70   
1          89                77   90   82              85         70   
2          83                90   80   64              92         80   
3          84                96   85   67              97         80   
4          75                92   80   72              91         80   

   Seni Budaya         OUTPUT  
0           70  Interpersonal  
1           77         Logika  
2           70         Verbal  
3           80         Verbal  
4           82         Verbal

In [21]:
X = df.iloc[:,0:7].values
y = df.iloc[:,7].values

print(X[0:5])
print(y[0:5])

[[77 65 82 93 74 70 70]
 [89 77 90 82 85 70 77]
 [83 90 80 64 92 80 70]
 [84 96 85 67 97 80 80]
 [75 92 80 72 91 80 82]]
['Interpersonal' 'Logika' 'Verbal' 'Verbal' 'Verbal']


In [22]:
print(X.shape)
print(y.shape)

(100, 7)
(100,)


In [23]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

In [24]:
print(y1)

[0 2 5 5 5 3 0 1 2 4 1 5 0 2 2 5 4 5 1 0 5 0 3 3 2 0 0 1 1 3 3 2 3 5 2 2 1
 5 2 5 4 0 1 4 0 3 5 3 1 4 5 3 4 5 3 4 0 1 2 4 1 5 5 5 1 0 5 4 3 5 0 1 0 5
 5 0 3 5 2 0 2 0 5 4 3 1 2 0 3 0 5 5 5 1 2 5 4 4 3 5]


In [25]:
Y = pd.get_dummies(y1).values
print(Y[0:5])

[[1 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]]


In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)
print(X_train[0:5])

[[75 60 90 83 73 85 88]
 [80 99 80 62 89 80 75]
 [84 96 85 67 97 80 80]
 [82 78 84 79 70 95 80]
 [80 77 80 63 70 80 90]]


In [28]:
print(y_train[0:5])

[[0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 1 0 0 0 0]
 [0 0 0 1 0 0]]


In [29]:
print(X_test[0:5])
print(y_test[0:5])


[[ 70  72  89  94  69  60  77]
 [100  86  90  94  73  85  84]
 [ 83  90  80  64  92  80  70]
 [ 88  72  95  70  62  80  80]
 [ 75  76  84  97  88  65  66]]
[[1 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 1 0]
 [1 0 0 0 0 0]]


In [30]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
  ])
model

In [31]:
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [33]:
model.fit(X_train, y_train, batch_size=50, epochs=100)

Epoch 1/100


TypeError: ignored